### ISSUE TITLE
lerna ERR! yarn run build exited 1 in '@flopflip/launchdarkly-adapter'

### ISSUE THREAD

**Issue by joshua-mbg** [tdeekens/flopflip#492]
This is on a fresh clone. I'm trying to just clone and build the current repo. Out of ideas.

```bash
flopflip$ npm cpx -v
6.4.1
flopflip$ npm install
npm WARN deprecated nomnom@1.6.2: Package no longer supported. Contact support@npmjs.com for more info.

> fsevents@1.2.4 install /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/fsevents
> node install

[fsevents] Success: "/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> iltorb@1.3.10 install /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/iltorb
> detect-libc prebuild-install || node-gyp rebuild


> iltorb@2.4.0 install /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup-plugin-filesize/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ /Users/josh/.npm/_prebuilds/9415e2-iltorb-v2.4.0-node-v57-darwin-x64.tar.gz
info found cached prebuild 
info unpacking @ /Users/josh/.npm/_prebuilds/9415e2-iltorb-v2.4.0-node-v57-darwin-x64.tar.gz
info unpack resolved to /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup-plugin-filesize/node_modules/iltorb/build/bindings/iltorb.node
info unpack required /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup-plugin-filesize/node_modules/iltorb/build/bindings/iltorb.node successfully
info install Successfully installed iltorb binary!

> husky@0.14.3 install /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
trying to install from sub 'node_module' directory, skipping Git hooks installation

> flopflip@ postinstall /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip
> check-node-version --package --print && yarn build

node: 8.12.0
npm: 6.4.1
yarn: 1.6.0
yarn run v1.6.0
$ NODE_ENV=production lerna run build
lerna notice cli v3.3.2
lerna info versioning independent
lerna info Executing command in 7 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@flopflip/launchdarkly-adapter'
lerna ERR! yarn run build stdout:
$ rimraf dist/**
$ cross-env npm run build:es && npm run build:cjs

> @flopflip/launchdarkly-adapter@2.4.0 build:es /Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/packages/launchdarkly-adapter
> cross-env NODE_ENV=development rollup -c ../../rollup.config.js -f es -i modules/index.js -o dist/@flopflip-launchdarkly-adapter.es.js

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:

modules/index.js → dist/@flopflip-launchdarkly-adapter.es.js...
(!) Unresolved dependencies
https://github.com/rollup/rollup/wiki/Troubleshooting#treating-module-as-external-dependency
lodash.isequal (imported by modules/adapter/adapter.js)
lodash.camelcase (imported by modules/adapter/adapter.js)
warning (imported by modules/adapter/adapter.js)
@babel/runtime/helpers/defineProperty (imported by modules/adapter/adapter.js)
@babel/runtime/helpers/objectSpread (imported by modules/adapter/adapter.js)
@babel/runtime/helpers/slicedToArray (imported by modules/adapter/adapter.js)
@babel/runtime/helpers/typeof (imported by ../../../ldclient-js/dist/ldclient.es.js)
(!) Error when using sourcemap for reporting an error: Can't resolve original location of error.
modules/adapter/adapter.js: (6:9)
[!] Error: 'initialize' is not exported by ../../../ldclient-js/dist/ldclient.es.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
modules/adapter/adapter.js (6:9)
4:   FlagVariation,
5:   User,
6:   Flag,
          ^
7:   Flags,
8:   OnFlagsStateChangeCallback,
Error: 'initialize' is not exported by ../../../ldclient-js/dist/ldclient.es.js
    at error (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:3438:30)
    at Module.error (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:13342:9)
    at handleMissingExport (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:13029:21)
    at Module.traceVariable (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:13450:17)
    at ModuleScope.findVariable (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:12709:29)
    at FunctionScope.Scope.findVariable (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:4000:68)
    at Scope.findVariable (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:4000:68)
    at Identifier$$1.bind (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:9649:40)
    at CallExpression.NodeBase.bind (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:9161:23)
    at CallExpression.bind (/Library/WebServer/Documents/g2m-interactive-recording/node_modules/flopflip/node_modules/rollup/dist/rollup.js:10219:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @flopflip/launchdarkly-adapter@2.4.0 build:es: `cross-env NODE_ENV=development rollup -c ../../rollup.config.js -f es -i modules/index.js -o dist/@flopflip-launchdarkly-adapter.es.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @flopflip/launchdarkly-adapter@2.4.0 build:es script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josh/.npm/_logs/2018-09-17T19_36_25_661Z-debug.log
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@flopflip/launchdarkly-adapter'
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flopflip@ postinstall: `check-node-version --package --print && yarn build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flopflip@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/josh/.npm/_logs/2018-09-17T19_36_26_097Z-debug.log
flopflip$ 
```

**Comment by tdeekens** [comment]
Sorry to hear that you're stuggling your fork. Looking at your log output I presume you're using `npm install`? You will have to use `yarn install` to install the dependencies. The project is organised as a mono-repo and uses yarn's workspaces feature. Lerna is only used to orchestrate releasing and running scripts across the packages (not initially to also bootstrap the packages).

**Comment by rameshdevalla45** [comment]
PS C:\Users\user\Documents\GitHub\next.js> yarn install
yarn : File C:\Users\user\AppData\Roaming\npm\yarn.ps1 cannot be loaded because running         
scripts is disabled on this system. For more information, see about_Execution_Policies at       
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ yarn install
+ ~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
